apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ADMIN_NAME: null
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:CT9DWJJ8FW9uFDgh3VHMcNo6O24=,iv:7M3SVpUKTX+JAklocWY3xZB6fU6SEy7d9sgwv2/vI94=,tag:E14ZyzbcfeK99MOJfIAV9A==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:GSs+u1LxpZt2jWzS1t3D2OZye6BlZQ==,iv:D83FEvTPgV5KXduAQIU2Gx1xTMawZm16IHWAXbXCLLY=,tag:8MgU3FrEf1ZSm2k6NAriRw==,type:str]
    SECRET_BASE_DOMAIN_NAME: null
    SECRET_NFS_SERVER: null
    SECRET_NFS_ROOTDIR: null
    SECRET_NFS_MEDIA_DIR: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnekggy4aeeqfqrwjrze8ye63xl9mkn93gt8yfv8exgk4p2uv4uscv28nr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RVlxSE1zRXNaUGRPbHpO
            NWYvbkFpSm9MeHpFL0pCRkJZZkpJNVdIeUFrCkIwV05JcEVWSWl2TVN4alZIV3Uv
            R0V2RlR2Z2ZYaTdtQXdNdUpUeDRVbUkKLS0tIEEzamlwbEVZeWVTdVBRK3BpeENl
            STdYbHZvUjVUT0xaWGFILy9LNGpwcjQKH/EsbBvpaHY8c+wlINSv9JVZit14hYws
            MK4SxyDee7iYegnxJJn/uF7cfFa9aFGZjZ6VqleQAK0Do2CMFwjURQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T16:58:50Z"
    mac: ENC[AES256_GCM,data:GZbjPneCrcuJOsniFsU0yXU8JPsiPweIKRulOC2+uhPfRluQ2N9rgd7nu/+OvrCiI2XVMfbSjd1cokiY5zMz5c1Z7UkN2gZtKJwRYnQx0ifJCsnHWJ8Tn0tlfBLMcGwa7Z6Ik2KgjGUWnXfN57YUeE9tG7bwRp4XfyPrei6/uOU=,iv:LS4hhWAiCws4bhXBFo4b4poGp+8AKgOO0sW5TXjbxEk=,tag:z4klXkV7rsvj5YbhHYr6cw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
