---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb
      version: 3.0.10
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.2.128-192.168.2.159
    prometheusRule:
      enabled: false # to change back to true
    controller:
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
    speaker:
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
