---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: charts
  path: ./clusters/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
